version: '3.8'

services:
  mcp-tool-enumeration-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-tool-enumeration-service
    ports:
      - "8503:8503"
    environment:
      - HOST=0.0.0.0
      - PORT=8503
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-tool-enumeration.rule=Host(`mcp-tool-enumeration.localhost`)"
      - "traefik.http.routers.mcp-tool-enumeration.entrypoints=web"
      - "traefik.http.services.mcp-tool-enumeration.loadbalancer.server.port=8503"

  # Optional: Add a reverse proxy for production
  traefik:
    image: traefik:v2.10
    container_name: mcp-tool-enumeration-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mcp-network
    profiles:
      - production

networks:
  mcp-network:
    driver: bridge
    name: mcp-tool-enumeration-network

volumes:
  prometheus_data:
    name: mcp-tool-enumeration-prometheus-data
  grafana_data:
    name: mcp-tool-enumeration-grafana-data