version: '3.8'

services:
  mcp-tool-enumeration-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-tool-enumeration-service-prod
    ports:
      - "8503:8503"
    environment:
      - HOST=0.0.0.0
      - PORT=8503
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      # Mount only logs directory (no source code mounting for security)
      - ./logs:/app/logs
    networks:
      - mcp-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-tool-enumeration.rule=Host(`mcp-tool-enumeration.astha.ai`)"
      - "traefik.http.routers.mcp-tool-enumeration.entrypoints=websecure"
      - "traefik.http.routers.mcp-tool-enumeration.tls=true"
      - "traefik.http.routers.mcp-tool-enumeration.tls.certresolver=letsencrypt"
      - "traefik.http.services.mcp-tool-enumeration.loadbalancer.server.port=8503"

networks:
  mcp-network:
    driver: bridge
    name: mcp-tool-enumeration-network-prod