global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MCP Tool Enumeration Service
  - job_name: 'mcp-tool-enumeration-service'
    static_configs:
      - targets: ['mcp-tool-enumeration-service:8503']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Traefik (if enabled)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s